OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: OrdererOrg
    Domain: excite-org
    CommonName: excite-org
    Specs:
      - Hostname: orderer0
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # ThanksOrg
  # ---------------------------------------------------------------------------
  - Name: ThanksOrg
    Domain: thanks-org
    Specs:
    - Hostname: thanks-peer
      CommonName: "{{.Hostname}}"